<script>
  import C from "../../components/Citation.svelte";
  import Dots from "../../components/Dots.svelte";
</script>

<p>In May 2019 I weighed 144 pounds with 11.1% bodyfat. I was prepping for my bodybuilding debut, and I was making great progress. By the time September 2020 rolled around, I was obese; over 200 pounds with 25% bodyfat. I had been prescribed medication which promoted weight gain, and had been taking it for a year. Once I stopped taking the meds I thought my eating habits and body composition would return to normal. They did not. I had developed an eating disorder where I would binge junkfood compulsively.</p>
<p>"No problem", I thought, "I know how to lose weight. After all, I'm a bodybuilder; just eat less and move more!" Right? I decided to do what I had always done: maintain a 500 calorie deficit and do cardio. Unfortunately, attempt after attempt to lose weight this way failed. My goal was correct, but I simply could not resist the urge to eat fast food and down soda.</p>
<p>I was getting desperate. I had gained 60 pounds of fat in six months. I was on the road to pre-diabetes.<C ref="pre"/> Not only did I crave food all the time, but I was also hungry and lethargic. I started to enjoy life less. Dating was out of the question, because I did not want to put that version of myself out into the world.</p>
<Dots />
<p>My mom and I were walking on the beach in September 2020. She suggested I try fasting to break the cycle of binging. I had fasted over multiple days before as a personal challenge, and decided it was worth trying. On September 19, 2020 I began a 50 hour water fast. Surprisingly, this actually seemed to kick my carb addiction, and I lost around 10 pounds off the bat. I suspect this was almost all water weight from glycogen depletion.<C ref="water"/></p>
<p>I had been tracking my ketones, and entered <a href="">ketosis</a> within 24 hours. Then the thought occurred to me: why not eat ketogenically? The more I thought about it, the more it made sense. I didn't have a food addiction, I had a carbohydrate addiction. I never binged roast beef or eggs, I would devour Cheetos and ice cream. I had nothing to lose, so after 50 hours of fasting, I broke that fast with a keto casserole. It tasted great, but the best part was something totally expected.</p>
<p>I was full. I finally wasn't hungry or craving food. Keto recipes are so rich that you can't help but stop after having enough. I looked up "5 Ingredient Keto Recipes", and started making a bunch of them. The food was amazing so it was easy to stick to. I wasn't counting calories at this point, but I estimate I was eating somewhere around 1500-2000 a day. The rules were simple: don't eat carbohydrate.</p>
<Dots />
<p>By the time October came around, I was eating even less because I was always full. It was around this time that I started OMAD (one meal a day). This was unplanned, and may sound extreme. I was as surprised as you may be. I just didn't feel like eating. I had a complete 180 from thinking about food all day to not really being interested until around 4 in the afternoon. Instead of using willpower to eat 500 calories less than I required every day, I just ate when I felt like it.</p>
<p>My addiction to carbohydrate had been broken, but I still wanted variety in my diet. I have a sweet tooth after all. I experimented with some diet sodas, and found a few that I really liked. Though somewhat controversial, I found that sodas sweetened with aspartame did not kick me out of ketosis, and did not slow down my progress. I also don't buy that aspartame is particularly bad for you,<C ref="aspartame"/> but that's another article.</p>
<p>Keto food is great, but I still wanted carbs every so often. I made a deal with myself: every two weeks I would have two cheat days. No limits on what I could eat, or how much. I did this for a few reasons. First, instead of cheating spiralling into chaos, I could time-box it. Scheduled cheat days gave me willpower when I wanted to eat junk food; "well, I'm a few days away from my scheduled cheat days. I can wait to have some Cheetos until Saturday." Second, it (probably)<C ref="probably"/> rebooted my metabolism,<C ref="refeed"/>, otherwise known as "refeeding." After extended periods of low caloric intake your body will adapt and require less food, or "slow" your metabolism.<C ref="metabolism"/> Third, and most surprisingly, the cheat days would usually remind me that carbs aren't really worth it. I find this hard to explain, and somewhat contradictory. My entire issue was binging carbohydrate, but when I scheduled a relapse they weren't even that great. The first few bites were glorious, but the "high" really didn't last. I think I just wanted the novelty, and that was enough to satisfy me.</p>
<Dots />
<p>After 30 days I had lost 20 pounds. I'm unsure if I would believe that if it hadn't happened to me. I had no timeline or goal weight, and 30 days had seemed like a good stopping point. However, when October 19 arrived, I didn't want to stop. It was incredibly rewarding to wake up every day and see movement on the scale. It was less of decision to keep going than a lack of a decision to stop. I enjoyed the food, felt great, and was making insane progress, so why change anything?</p>
<p>I continued until I hit 90 days, and during that time I lost 37 pounds. I was worried to reintroduce carbs into my normal diet, but it went very well. I was no longer addicted, and was ready to finally pursue my dream of becoming a bodybuilder. On September 19, 20201, 365 since I began my transformation, I looked like this. Two weeks later I was holding a trophy for competing in my first bodybuilding show.</p>
<Dots />
<p>Though I did not count calories nor intentionally restrict them, I must stress that my weight loss was thanks to calorie deficit.<C ref="cico"/> Fundamentally, that is the <em>only</em> way to lose weight.<C ref="cico"/> The tricky part of weight loss is finding a strategy to sustain that calorie deficit. For me, keto keeps me full so I end up eating very little without having to deprive myself. Other strategies might help other people maintain calorie deficits just as well as I did, but for me, keto is king.</p>

<style>
  p {
    font-size: larger !important;
  }
</style>
